### ISSUE TITLE
Meta: Swave

### ISSUE THREAD

**Issue by sirinath** [strymonas/staged-streams.scala#5]
Also have a look at http://swave.io/

**Comment by biboudis** [comment]
@sirinath I am closing this since it is not a concrete issue or recommendation

**Comment by sirinath** [comment]
That's why I put Meta. I just wanted to bring the project to your attention so you can get ideas and improve this. Also see: https://github.com/rssh/scala-gopher

It might be worthwhile to have a discussion group (https://groups.io/ ?) and chat room (http://gitter.im/ ?)

**Comment by biboudis** [comment]
Since the issue tracker is not a discussion forum nor a suitable platform to ask questions I will open a group or chat room as you recommended. 

Thanks for bringing up this related work, though. Check our paper to see where it stands in the design space.

Thanks!
